In [1]:
import numpy as np

similarity_matrix = '../similarity/similarity_matrix.txt'

def get_matrix():
    mat = np.loadtxt(similarity_matrix, delimiter=',')
    return mat

In [2]:
matrix = get_matrix()

In [22]:
np.unique(matrix.ravel(), return_counts=True)[0]

array([  0.   ,  22.05 ,  26.132, ...,  99.682,  99.683, 100.   ])

In [12]:
np.where(matrix==99.683)

(array([26, 26, 26, 26, 26, 26, 26, 26, 26, 28, 28, 29, 29, 29, 29, 30, 30,
        30, 31, 31, 31, 32, 32, 33, 33, 33, 33, 33, 33, 34, 34, 34, 35, 35,
        35, 36, 37, 37, 37, 37, 39, 39, 39, 39, 40, 40, 40, 41, 41, 41, 42,
        42, 42, 42, 43, 43, 44, 44, 44, 45, 46, 47, 47, 47, 48, 48, 49, 49,
        49, 52, 52, 52, 53, 53, 54, 54, 54, 55, 55, 56, 56, 57, 57, 57, 58,
        59, 59, 60, 60, 60, 61, 62, 63, 64, 64, 65, 66, 68, 69, 69, 69, 70,
        70, 71, 71, 72, 72, 72, 73, 73, 73, 75, 75, 75, 75, 75, 75, 75, 75,
        75]),
 array([28, 39, 60, 64, 69, 70, 71, 72, 73, 26, 75, 34, 35, 39, 66, 33, 72,
        73, 34, 39, 60, 35, 69, 30, 36, 41, 42, 43, 44, 29, 31, 37, 29, 32,
        37, 33, 34, 35, 45, 46, 26, 29, 31, 75, 63, 65, 68, 33, 47, 48, 33,
        47, 49, 53, 33, 49, 33, 48, 53, 37, 37, 41, 42, 52, 41, 44, 42, 43,
        52, 47, 49, 54, 42, 44, 52, 55, 56, 54, 57, 54, 57, 55, 56, 62, 59,
        58, 61, 26, 31, 75, 59, 57, 40, 26, 75, 40, 29, 40, 26, 32, 75, 26

In [23]:
matrix[26,28]

99.683