In [2]:
import pandas as pd
import sys

sys.path.append('../')

In [3]:
import helper

In [4]:
labelfile = '../Data/ThioesteraseProductFractionLabel.xlsx'
seqfile = '../Data/Enzyme_Dataset.txt'

In [5]:
df = pd.read_excel(labelfile,header=None)

In [6]:
Xnameref,y = df.iloc[:,0].values,df.iloc[:,1].values

In [7]:
seq,label,Xname = helper.parseEnzymeFile(seqfile)

In [8]:
seqdictmap = dict(zip(Xname,seq))

In [9]:
labeldictmap = dict(zip(Xnameref,y))

In [10]:
enzname = []
X = []
y = []

for xn in seqdictmap.keys():
    if xn in labeldictmap:
        enzname.append(xn)
        X.append(seqdictmap[xn])
        y.append(labeldictmap[xn])
    else:
        print(xn)

Cuphea_viscosissima_(CvFatB1)
Cuphea_viscosissima_(CvFatB2)
Cuphea_carthagenesis_(CcFatB)


In [11]:
import numpy as np
enzname,X,y = np.array(enzname),np.array(X),np.array(y)

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
def get_model(n_comp):
    steps = [('pca',PCA(n_components=n_comp)),('LR',LinearRegression())]
    pipe = Pipeline(steps)
    return pipe
    

In [13]:
from FeatEngg.ngramEnc import Ngram

In [14]:
teidx,tridx = helper.modified_split(enzname)

In [104]:
ngram = Ngram(X[tridx],7,1)
ngram.fit()

In [105]:
X_ng_tr = ngram.transform(X[tridx])

In [106]:
y_tr = y[tridx]

In [107]:
mypipe = get_model(40)

In [108]:
model = mypipe.fit(X_ng_tr,y_tr)

In [109]:
y_pred_tr = model.predict(X_ng_tr)

In [110]:
from sklearn.metrics import mean_squared_error

In [111]:
mean_squared_error(y_tr,y_pred_tr)

0.011622145850096742

In [112]:
X_ng_te = ngram.transform(X[teidx])

In [113]:
y_pred_te = model.predict(X_ng_te)

In [114]:
y_te = y[teidx]

In [115]:
mean_squared_error(y_te,y_pred_te)

0.06138513660690401

In [27]:
y_te

array([0.653     , 0.6       , 0.15      , 0.98      , 0.05519897,
       0.087     , 0.09      , 0.81      , 0.602     , 0.09      ,
       0.        , 0.753     , 0.361     , 0.854     , 0.        ,
       0.82714551, 0.05      , 0.799     , 0.82      , 0.387     ,
       0.044     , 0.681     , 0.066     , 0.291     ])

In [28]:
y_pred_te

array([0.3320532 , 0.47724165, 0.09453708, 0.82900302, 0.18044687,
       0.14496201, 0.18645989, 0.05364181, 0.68332716, 0.5807953 ,
       0.00986262, 0.69512173, 0.56545548, 0.58084996, 0.15025449,
       0.19093048, 0.19164834, 0.77267515, 0.790815  , 0.59802837,
       0.03655299, 0.58182941, 0.17224802, 0.3838413 ])

In [29]:
from FeatEngg.gaacEnc import GAAC

In [30]:
gaac = GAAC()
Xgaac = gaac.transform(X)

In [124]:
ngram = Ngram(Xgaac[tridx],7,1)
ngram.fit()

In [125]:
X_ngaac_tr = ngram.transform(Xgaac[tridx])

In [126]:
newpipe = get_model(10)

In [127]:
new_model = newpipe.fit(X_ngaac_tr,y_tr)

In [128]:
X_ngaac_te = ngram.transform(Xgaac[teidx])
y_pred_te = new_model.predict(X_ngaac_te)

In [129]:
mean_squared_error(y_te,y_pred_te)

0.08955125701682011

In [122]:
y_te

array([0.653     , 0.6       , 0.15      , 0.98      , 0.05519897,
       0.087     , 0.09      , 0.81      , 0.602     , 0.09      ,
       0.        , 0.753     , 0.361     , 0.854     , 0.        ,
       0.82714551, 0.05      , 0.799     , 0.82      , 0.387     ,
       0.044     , 0.681     , 0.066     , 0.291     ])

In [123]:
y_pred_te

array([ 0.32290969,  0.42573565,  0.02551049,  0.3626729 ,  0.19034292,
        0.30644388,  0.25388991, -0.01457649,  0.52776929,  0.43702575,
       -0.02136511,  0.54703045,  0.49387487,  0.69004811,  0.22020371,
        0.24884764,  0.20933521,  0.62571234,  0.55350008,  0.44267205,
        0.31154312,  0.65088031,  0.31154312,  0.38478158])

In [131]:
import pickle

file = pickle.load(open('../Data/TE_ML_Data_pickle.p','rb'))

In [133]:
pmap = dict(zip(file[0],file[1]))

In [138]:
Xp = np.array([pmap[e] for e in enzname])

In [143]:
pospipe = get_model(40)

posmodel = pospipe.fit(Xp[tridx],y[tridx])

In [144]:
y_pred_te = posmodel.predict(Xp[teidx])

In [145]:
mean_squared_error(y_te,y_pred_te)

0.03773853154911842

In [146]:
y_te

array([0.653     , 0.6       , 0.15      , 0.98      , 0.05519897,
       0.087     , 0.09      , 0.81      , 0.602     , 0.09      ,
       0.        , 0.753     , 0.361     , 0.854     , 0.        ,
       0.82714551, 0.05      , 0.799     , 0.82      , 0.387     ,
       0.044     , 0.681     , 0.066     , 0.291     ])

In [147]:
y_pred_te

array([ 3.46963542e-01,  5.25683362e-01,  4.37515041e-03,  9.86147718e-01,
        6.66430398e-02,  2.46768656e-01,  6.66430398e-02,  9.74527256e-02,
        6.27639662e-01,  1.93190672e-01, -6.64505709e-04,  6.98834467e-01,
        6.18918120e-01,  9.54853243e-01,  1.87682432e-01,  5.78565140e-01,
        1.09224351e-01,  7.06284738e-01,  6.54069941e-01,  2.77898214e-01,
        8.14542972e-02,  6.54103403e-01,  1.63326952e-01,  3.07865235e-01])